### ISSUE TITLE
SSL redshift certificate provided is expired

### ISSUE THREAD

**Issue by Gronan** [awsdocs/amazon-redshift-management-guide#10]
the page https://docs.aws.amazon.com/redshift/latest/mgmt/connecting-ssl-support.html provide a link (https://s3.amazonaws.com/redshift-downloads/redshift-ca-bundle.crt) but the certificate expired the 2018-11-02

**Comment by keithhc2** [comment]
It looks like the page now points to updated download links and the certs look fine to me. If the issue persists, feel free to reopen the issue.
