### ISSUE TITLE
Lack of information regarding Amazon Redshift JDBC driver recommendation

### ISSUE THREAD

**Issue by eduardowillame** [awsdocs/amazon-redshift-management-guide#11]
Hi,
In the following link regarding AWS Redshift documentation:
https://docs.aws.amazon.com/redshift/latest/mgmt/configure-jdbc-connection.html
There is an Important note which says:

"We strongly recommend using an Amazon Redshift JDBC driver that doesn't include the AWS SDK if possible. The drivers in the following list don't include the AWS SDK."

However, no reason is given. It's important to elaborate the reason in order to make customers aware of it.

**Comment by keithhc2** [comment]
Closing the issue because the related section in the docs has been removed. Feel free to reopen if you think we should add the section back in.
