### ISSUE TITLE
sql workbench message org/antlr/v4/runtime/lexer

### ISSUE THREAD

**Issue by kanniahvj2020** [awsdocs/amazon-redshift-management-guide#23]
Hi,

I am accessing the Redshift cluster using Sql Workbench/J and the connection test is successful, when i try to perform SQL Query or accessing the Database explorer, then i am getting message "org/antlr/v4/runtime/lexer"

Not sure what is the issue and any tips are appreciated to make a successful query from the schema.

<img width="960" alt="Redshfit-Cluster" src="https://user-images.githubusercontent.com/64630641/141938504-d5e0abbe-a2bb-4bf6-bf3d-b103e353e5ec.PNG">

**Comment by keithhc2** [comment]
@kanniahvj2020 Have you contacted AWS Support? This repo is more documentation-oriented, so unless you have a specific question about the documentation, the AWS Support team might be better equipped to help you. You can find out more about them here: https://aws.amazon.com/contact-us/

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
