### ISSUE TITLE
Retrieve cluster identifier with SQL statement.

### ISSUE THREAD

**Issue by JDarDagran** [awsdocs/amazon-redshift-management-guide#27]
Hello,

I am trying to retrieve cluster identifier of the Redshift cluster using SQL only.  In most cases it is possible to find the identifier from cluster endpoint but you can also use elastic IP which is not so informative. I went through `information_schema` and `pg_catalog` objects, however, I did not succeed in finding above information.

Please let me know if there is any way to query this.

Thanks!

**Comment by keithhc2** [comment]
@JDarDagran Have you contacted AWS Support? This repo is more documentation related, so unless you have a specific documentation issue, I think the support team would be better equipped to help you. You can find out more about them here: https://aws.amazon.com/contact-us/

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
