### ISSUE TITLE
Working with AWS Backup page has a point about S3 backups

### ISSUE THREAD

**Issue by rdbatch** [awsdocs/amazon-redshift-management-guide#32]
On the [Working with AWS Backup](https://github.com/awsdocs/amazon-redshift-management-guide/blob/master/doc_source/managing-aws-backup.md) page, the final bullet under the heading "Considerations for using AWS Backup with Amazon Redshift" seems to be partially taken from the S3 documentation (including a link to S3 versioning docs). This point should probably be re-worded to only discuss why you should use lifecycle rules for Redshift backups and remove the references to S3.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
